### ISSUE TITLE
Warning under Xamarin.Forms project

### ISSUE THREAD

**Issue by tfierens** [lbugnion/mvvmlight#49]
Hi,

I created a dummy app in .NET 2017 Community Edition, added MVVMLight Nuget package at the at solution level and selected all projects (.NET standard, iOS, Android and UWP) and while it installed successfully, I somehow could not access Galasoft or MvvmLight namespaces in the project.

I ended up removing it and adding MVVMLightLibs Nuget package instead and it seems that with this one  I was able to access the Galasoft & MvvmLight namespaces and while everything so far appears to be ok, I'm still getting a warning:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'MvvmLightLibs 5.4.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	XamarinForms101	C:\Users\User\source\repos\XamarinForms101\XamarinForms101\XamarinForms101\XamarinForms101.csproj	1	

Any ideas?

Thanks.

T.

PS: I haven't replaced the ServiceLocator just yet but if I recall one of your articles, I think this was removed. Is there a full example using the latest version of Xamarin Forms & MVVMLight that at least highlights how to get around the fact there isn't a ServiceLocator, on how to use RelayCommand, EventToCommand, Messenger, etc.... Thanks. T

**Comment by tfierens** [comment]
Working on a new personal project and my solution just got corrupted after closing my SP3. Created a new solution and trying to re-import all existing files into it but having a problem and after googling it, I'm actually surprised that I landed on my own question re-highlighting the very same problem.

Any suggestions??

**Comment by SittenSpynne** [comment]
My interpretation of this issue so far is something like this:

.NET Standard 1.0, not 2.0, is supported. Xamarin projects are standardizing on .NET Standard 2.0. I can see some time last year, the support for 1.0 existed but was considered prerelease. I can see in issue #2 something very similar to your issue (which is also what brought me here). It doesn't seem like there's a large body of work to get things functional in XF. (I don't have the sophistication yet to try it myself.)

If you're still hacking at it, I think the most productive 2 options are:

1. A lot of MvvmLight's utility is from files you can paste into your project rather than depending on the NuGet package. It seems like most of the .NET Standard incompatibility comes from the ServiceLocator dependency. So you can probably clone, make some quick modifications, and build. Or, if all you were really using is stuff like RelayCommand and ViewModelBase, it seems in the spirit of the license you ought to be able to use those files directly (with the same attribution.)
2. FreshMvvm is a little more opinionated than MvvmLight but functional in XF.

**Comment by lbugnion** [comment]
Hi,

.NET Standard 1.0 can be used in any .NET Standard application / class assembly because .NET Standard versions are always fully backwards compatible. So if you do Xamarin Forms which uses .NET Standard 2.0, you can use MVVM Light Standard anyway, since it's 1.0.

However in the first issue it seems that the wrong package was selected. Make sure to select MvvmLightLibsStd10 which is available at https://www.nuget.org/packages/MvvmLightLibsStd10/

**Comment by SittenSpynne** [comment]
You're right. I was confused by some other errors in my project and thought they were related to that .NET Standard package. Now that it's a new day and a fresh project it's working.

**Comment by lbugnion** [comment]
Thanks for the confirmation. Good luck!
