### ISSUE TITLE
VSIX packages for vs2019

### ISSUE THREAD

**Issue by lwqwag** [lbugnion/mvvmlight#73]
when will VSIX packages for vs2019 be available

**Comment by JKennedy24** [comment]
Please can we release an update for 2019. I have learnt that I rely on these VISX packages and library alot!

**Comment by lbugnion** [comment]
Sorry that this hasn't been done yet. I will work on this ASAP. Work is taking a toll on me but I hope I get a respite.

**Comment by lwqwag** [comment]
ok,thx for your effort

**Comment by UweKeim** [comment]
I've tried to manually modify the VSIX from VS2017 for VS2019, [as documented here](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/), but gave up since I got different installation errors.

Probably have to wait until @lbugnion acutally updates the extension.

**Comment by a5ync** [comment]
@UweKeim I don't know if you have noticed but there is a PR with 2019 version.
https://github.com/lbugnion/mvvmlight/pull/72
